name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3    
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
      # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Specifies whether the given registry is ECR (auto, true or false)

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag bernardolankheet/udp-trap-nginx-proxy:latest
        docker tag bernardolankheet/udp-trap-nginx-proxy:latest bernardolankheet/udp-trap-nginx-proxy:$(date +%s)
        docker push bernardolankheet/udp-trap-nginx-proxy:latest